#!/usr/bin/env python
#
# biolm-sdk documentation build configuration file, created by
# sphinx-quickstart on Fri Jun  9 13:47:02 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import re

import click
from docutils import nodes

# Build option: iframe mode (hides header for embedding)
# Set via environment variable: IFRAME_MODE=1 make html
iframe_mode = os.environ.get('IFRAME_MODE', '0') == '1'

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories to sys.path here. If the directory is
# relative to the documentation root, use os.path.abspath to make it
# absolute, like shown here.
#
# Add parent directory to sys.path so Sphinx can import biolm
import sys
sys.path.insert(0, os.path.abspath('..'))


def _sphinx_builder_name():
    """Return the Sphinx builder from the current invocation, if present."""
    argv = sys.argv
    for i, arg in enumerate(argv):
        if arg in ("-b", "--builder", "-M") and i + 1 < len(argv):
            return argv[i + 1]
        if arg.startswith("-b") and len(arg) > 2:
            return arg[2:]
    return None


# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.doctest",
    "sphinx_copybutton",
    "sphinx_inline_tabs",
    "sphinx.ext.autosectionlabel",
    "sphinxext.opengraph",
    "sphinx_design",
    "myst_parser",
    "sphinx_new_tab_link",
    "sphinx_reredirects",
    "sphinx-jsonschema",
    "sphinx_click",
]

# Offline-safe guide snippet checks (see docs/notes/snippet-doctests.rst).
# Network-backed examples stay as narrative ``code-block`` and are not executed.
doctest_global_setup = """
import os
import tempfile
from pathlib import Path

# Avoid accidental auth lookups during construct-only snippets.
os.environ.setdefault("BIOLM_TOKEN", "doctest-dummy-token")

_DOCTEST_TMP = Path(tempfile.mkdtemp(prefix="biolm-docs-doctest-"))
"""

doctest_global_cleanup = """
import shutil
shutil.rmtree(_DOCTEST_TMP, ignore_errors=True)
"""

doctest_test_doctest_blocks = False

# These extensions hook HTML page rendering and break ``sphinx-build -b json``.
_JSON_INCOMPATIBLE_EXTENSIONS = (
    "sphinxext.opengraph",
    "sphinx_reredirects",
    "sphinx_new_tab_link",
    "sphinx.ext.viewcode",
)
if _sphinx_builder_name() == "json":
    extensions = [
        ext for ext in extensions if ext not in _JSON_INCOMPATIBLE_EXTENSIONS
    ]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "BioLM SDK"
copyright = "2023, BioLM.ai"
author = "Nikhil Haas"

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
from biolm import __version__

# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# Dark mode syntax highlighting (Furo-specific)
pygments_dark_style = "material"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "top_of_page_button": None,
    "sidebar_hide_name": True,
    "light_logo": None if iframe_mode else "biolm_logo_light.svg",
    "dark_logo": None if iframe_mode else "biolm_logo_dark.svg",
    
    # Custom CSS variables for branding
    "light_css_variables": {
        # Primary brand colors - replace with your website's brand colors
        "color-brand-primary": "#2563eb",  # Replace with your main brand color
        "color-brand-content": "#2563eb",  # Links and interactive elements
        
        # Sidebar customization
        "color-sidebar-brand-text": "#1f2937",
        "color-sidebar-background": "#f8fafc",
        "color-sidebar-background-border": "#e2e8f0",
        
        # Additional brand colors
        "color-admonition-title-background--note": "#dbeafe",
        "color-admonition-title--note": "#1e40af",
        
        # Header and navigation
        "color-header-background": "#ffffff",
        "color-header-text": "#1f2937",
        
        # Code blocks (darker text for readability in light theme)
        "color-code-background": "#f1f5f9",
        "color-code-foreground": "#1e293b",
        
        # Font families to match your website exactly
        "font-stack": '"Inter", ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
        "font-stack--monospace": '"Roboto Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    
    "dark_css_variables": {
        # Dark mode brand colors
        "color-brand-primary": "#60a5fa",  # Lighter version for dark mode
        "color-brand-content": "#60a5fa",
        
        # Dark sidebar
        "color-sidebar-background": "#1e293b",
        "color-sidebar-background-border": "#334155",
        "color-sidebar-brand-text": "#f1f5f9",
        
        # Dark mode code blocks (brighter text for readability)
        "color-code-background": "#1e293b",
        "color-code-foreground": "#f1f5f9",
        
        # Additional dark mode styling
        "color-highlight-on-target": "#374151",
        # Admonitions (note, tip, etc.) - dark background, light title text
        "color-admonition-title-background--note": "#1e3a5f",
        "color-admonition-title--note": "#93c5fd",
        "color-admonition-background": "#1e293b",
        
        # Font families to match your website exactly (same as light mode)
        "font-stack": '"Inter", ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
        "font-stack--monospace": '"Roboto Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom CSS files
html_css_files = [
    'custom.css',
]
if iframe_mode:
    html_css_files.append('iframe-mode.css')

# Add Google Fonts (Inter and Roboto Mono to match website)
html_css_files.extend([
    'https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap',
    'https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400;500;600;700&display=swap',
])

# Additional branding options
html_title = "BioLM SDK Documentation"
html_short_title = "BioLM SDK"

# Custom favicon (add your favicon.ico to _static folder)
# html_favicon = "_static/favicon.ico"

# Custom footer
html_show_sphinx = False
html_show_copyright = True

# SEO and metadata
html_meta = {
    "description": "Official documentation for the BioLM Python SDK and CLI",
    "keywords": "BioLM, AI, machine learning, biology, protein, DNA, API",
    "author": "BioLM.ai Team",
    "viewport": "width=device-width, initial-scale=1",
}

# Social media cards / Open Graph
html_theme_options.update({
    "announcement": None,  # Add site-wide announcements here if needed
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/BioLM/biolm-sdk",
            "html": """
                <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
                </svg>
            """,
            "class": "",
        },
    ],
})


# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "biolmsdkdoc"


# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [
    (master_doc, "biolmsdk.tex", "BioLM SDK Documentation", "Nikhil Haas", "manual"),
]


# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "biolm-sdk", "BioLM SDK Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "biolm-sdk",
        "BioLM SDK Documentation",
        author,
        "biolm-sdk",
        "One line description of project.",
        "Miscellaneous",
    ),
]

# sphinx-click: render envvar descriptions as normal text instead of block quotes
def _envvar_description_as_paragraph(app, ctx, lines):
    for i, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("Provide a default for ") and ":option:" in stripped:
            lines[i] = stripped


def _keep_description_paragraphs(lines: list[str], max_paragraphs: int = 2) -> None:
    if not lines:
        return
    paragraphs: list[list[str]] = []
    current: list[str] = []
    for line in lines:
        if not line.strip():
            if current:
                paragraphs.append(current)
                current = []
            continue
        current.append(line)
    if current:
        paragraphs.append(current)
    if not paragraphs:
        return

    kept = paragraphs[:max_paragraphs]
    flat: list[str] = []
    for i, para in enumerate(kept):
        flat.extend(para)
        if i < len(kept) - 1:
            flat.append("")
    if flat and flat[-1].strip():
        flat.append("")
    lines[:] = flat


def _trim_click_description_lines(app, ctx, lines):
    """Use concise multi-paragraph descriptions for groups and subcommands in CLI docs."""
    path_parts = ctx.command_path.split()
    if isinstance(ctx.command, click.Group) or len(path_parts) >= 3:
        _keep_description_paragraphs(lines, max_paragraphs=2)


_CLICMD_RE = re.compile(r"^(.+?)\s*<([^>]+)>$")


def _internal_link_role(name, rawtext, text, lineno, inliner, options=None, content=None):
    """Internal doc link: ``:role:`title <path.html#anchor>```."""
    if options is None:
        options = {}
    if content is None:
        content = []
    match = _CLICMD_RE.match(text.strip())
    if not match:
        msg = inliner.reporter.warning(f"Invalid :{name}: syntax: {text}", line=lineno)
        return [inliner.problematic(rawtext)], [msg]
    title, refuri = match.group(1), match.group(2)
    node = nodes.reference(rawtext, title, refuri=refuri, internal=True)
    return [node], []


def _clicmd_role(name, rawtext, text, lineno, inliner, options=None, content=None):
    """Internal doc link: ``:clicmd:`title <page.html#anchor>```."""
    return _internal_link_role(name, rawtext, text, lineno, inliner, options, content)


def _sdklink_role(name, rawtext, text, lineno, inliner, options=None, content=None):
    """Internal SDK index link: ``:sdklink:`title <../page.html>```."""
    return _internal_link_role(name, rawtext, text, lineno, inliner, options, content)


def _command_title(text: str) -> nodes.title:
    title = nodes.title()
    title += nodes.Text(text)
    return title


def _strip_click_program_nodes(top_section: nodes.section) -> None:
    """Remove sphinx-click program index nodes that duplicate the group heading in TOC."""
    for node in list(top_section.children):
        if getattr(node, "tagname", "") == "index":
            node.parent.remove(node)


def _is_cli_subcommand_id(section_id: str) -> bool:
    return section_id.startswith("biolm-") and len(section_id.split("-")) >= 3


def _is_click_group_section(section: nodes.section) -> bool:
    section_id = section.get("ids", [""])[0]
    if _is_cli_subcommand_id(section_id):
        return False
    if any(isinstance(node, nodes.rubric) for node in section.children):
        return True
    return any(
        isinstance(node, nodes.section) and _is_cli_subcommand_id(node.get("ids", [""])[0])
        for node in section.children
    )


def _find_click_section(parent: nodes.section) -> nodes.section | None:
    """Return the sphinx-click group/command section nested under the page."""
    for child in parent.children:
        if isinstance(child, nodes.section) and _is_click_group_section(child):
            return child
    return None


def _transform_cli_click_pages(app, doctree, docname=""):
    """Merge sphinx-click output into Modal-style CLI pages."""
    if doctree.get("_cli_click_merged"):
        return
    if not docname.startswith("cli/") or docname == "cli/index":
        return

    if not isinstance(doctree, nodes.document):
        return

    top_section = next((c for c in doctree.children if isinstance(c, nodes.section)), None)
    if top_section is None:
        return

    click_section = _find_click_section(top_section)
    if click_section is None:
        return

    if click_section.children and isinstance(click_section.children[0], nodes.title):
        click_section.remove(click_section.children[0])

    insert_at = len(top_section.children)
    for child in list(click_section.children):
        click_section.remove(child)
        top_section.insert(insert_at, child)
        insert_at += 1

    parent = click_section.parent
    if parent is not None:
        parent.remove(click_section)

    _strip_click_program_nodes(top_section)

    for child in top_section.children:
        if not isinstance(child, nodes.section):
            continue
        section_id = child.get("ids", [""])[0]
        if not _is_cli_subcommand_id(section_id):
            continue
        full_name = section_id.replace("-", " ")
        child["names"] = [nodes.fully_normalize_name(full_name)]
        if child.children and isinstance(child.children[0], nodes.title):
            child.remove(child.children[0])
        child.insert(0, _command_title(full_name))

    doctree["_cli_click_merged"] = True


def _fix_cli_toc_reference(ref: nodes.reference) -> None:
    refuri = ref.get("refuri") or ""
    if not refuri.startswith("#biolm-"):
        return
    section_id = refuri[1:]
    if len(section_id.split("-")) >= 3:
        ref.clear()
        ref += nodes.Text(section_id.replace("-", " "))


def _flatten_cli_toc_group_wrapper(toc: nodes.bullet_list) -> None:
    """Drop the duplicate group-level local-TOC entry under the page title."""
    for top_item in toc.children:
        if not isinstance(top_item, nodes.list_item):
            continue
        for child in top_item.children:
            if not isinstance(child, nodes.bullet_list):
                continue
            group_list = child
            for group_item in list(group_list.children):
                if not isinstance(group_item, nodes.list_item):
                    continue
                ref = next((c for c in group_item.children if isinstance(c, nodes.reference)), None)
                if ref is None:
                    continue
                refuri = ref.get("refuri") or ""
                section_id = refuri[1:] if refuri.startswith("#") else ""
                if not section_id.startswith("biolm-") or len(section_id.split("-")) != 2:
                    continue
                nested = next((c for c in group_item.children if isinstance(c, nodes.bullet_list)), None)
                if nested is None:
                    continue
                group_item.remove(nested)
                insert_at = group_list.children.index(group_item) + 1
                group_list.insert(insert_at, nested)
                group_list.remove(group_item)


def _fix_cli_page_toc(app, pagename, templatename, context, doctree) -> None:
    if not pagename.startswith("cli/") or pagename == "cli/index":
        return
    toc = context.get("toc")
    if not hasattr(toc, "traverse"):
        return
    for ref in toc.traverse(nodes.reference):
        _fix_cli_toc_reference(ref)
    if isinstance(toc, nodes.bullet_list):
        _flatten_cli_toc_group_wrapper(toc)


def setup(app):
    app.connect("sphinx-click-process-envvars", _envvar_description_as_paragraph)
    app.connect("sphinx-click-process-description", _trim_click_description_lines)

    def _on_doctree_read(app, doctree):
        _transform_cli_click_pages(app, doctree, app.env.docname)

    # Run before TocTreeCollector (default priority 500) builds env.tocs.
    app.connect("doctree-read", _on_doctree_read, priority=10)
    app.connect("html-page-context", _fix_cli_page_toc)
    app.add_js_file("caption-links.js")
    app.add_role("clicmd", _clicmd_role)
    app.add_role("sdklink", _sdklink_role)


# Redirects
redirects = {
    "api-reference/index": "sdk/index",
    "sdk/api-reference/index": "sdk/index",
    "cli/reference": "reference/cli",
    "protocols/about": "yaml/protocol-schema",
    "protocols/inputs": "yaml/protocol-schema",
    "protocols/execution": "yaml/protocol-schema",
    "protocols/tasks": "yaml/protocol-schema",
    "protocols/output": "yaml/protocol-schema",
    "protocols/schema": "yaml/protocol-schema",
    "resources/rest-api": "reference/rest-api",
    "cli/overview": "cli/index",
    "cli/usage/authenticating": "cli/login",
    "cli/usage/models": "cli/model",
    "cli/usage/protocols": "cli/protocol",
    "cli/usage/workspaces": "cli/workspace",
    "cli/usage/datasets": "cli/dataset",
    "model-docs/esmfold/ESMFold_Additional": "https://biolm.ai/models/esmfold/",
    "model-docs/esmfold/ESMFold_API": "https://biolm.ai/models/esmfold/",
    "model-docs/esmfold/index": "https://biolm.ai/models/esmfold/",
    "model-docs/esm1v/ESM-1v_Additional": "https://biolm.ai/models/esm1v-all/",
    "model-docs/esm1v/ESM-1v_API": "https://biolm.ai/models/esm1v-all/",
    "model-docs/esm1v/index": "https://biolm.ai/models/esm1v-all/",
    "model-docs/esm2/ESM2_Additional": "https://biolm.ai/models/esm2-650m/",
    "model-docs/esm2/ESM2_API": "https://biolm.ai/models/esm2-650m/",
    "model-docs/esm2/index": "https://biolm.ai/models/esm2-650m/",
    "model-docs/progen2/ProGen2_Additional": "https://biolm.ai/models/progen2-medium/",
    "model-docs/progen2/ProGen2_API": "https://biolm.ai/models/progen2-medium/",
    "model-docs/progen2/index": "https://biolm.ai/models/progen2-medium/",
    "model-docs/esmif/ESM_InverseFold_Additional": "https://biolm.ai/models/esm-if1/",
    "model-docs/esmif/ESM_InverseFold_API": "https://biolm.ai/models/esm-if1/",
    "model-docs/esmif/index": "https://biolm.ai/models/esm-if1/",
    "model-docs/dnabert/DNABERT_Additional": "https://biolm.ai/models/dnabert2/",
    "model-docs/dnabert/classifier_ft": "https://biolm.ai/models/dnabert2/",
    "model-docs/dnabert/index": "https://biolm.ai/models/dnabert2/",
    "model-docs/biolmtox/BioLMTox_Additional": "https://biolm.ai/models/biolmtox/",
    "model-docs/biolmtox/BioLMTox_API": "https://biolm.ai/models/biolmtox/",
    "model-docs/biolmtox/index": "https://biolm.ai/models/biolmtox/",

    "getting-started/installation": "guide/installation",
    "getting-started/authentication": "guide/authentication",
    "getting-started/quickstart": "guide/quickstart",
    "getting-started/concepts": "guide/concepts",
    "getting-started/overview": "guide/overview",
    "getting-started/migration-1.0": "notes/migration-1.0",
    "intro/migration-1.0": "notes/migration-1.0",
    "intro/quickstart": "guide/quickstart",
    "intro/installation": "guide/installation",
    "intro/authentication": "guide/authentication",
    "intro/concepts": "guide/concepts",
    "intro/sdk-overview": "guide/sdk-overview",
    "intro/client-interfaces": "guide/client-interfaces",
    "intro/batching": "guide/batching",
    "intro/error-handling": "guide/error-handling",
    "intro/concurrency": "guide/concurrency",
    "intro/rate-limiting": "guide/rate-limiting",
    "intro/faq": "guide/faq",
    "intro/overview": "guide/overview",
    "authoring-guide": "notes/authoring-guide",
    "sdk/overview": "guide/sdk-overview",
    "sdk/usage/usage": "guide/client-interfaces",
    "sdk/usage/batching": "guide/batching",
    "sdk/usage/error-handling": "guide/error-handling",
    "sdk/usage/async-sync": "guide/concurrency",
    "intro/async-sync": "guide/concurrency",
    "sdk/usage/rate_limiting": "guide/rate-limiting",
    "sdk/usage/io": "sdk/io",
    "sdk/faq": "guide/faq",
    "reference/protocol-schema": "yaml/protocol-schema",
    "reference/changelog": "changelog",
    "reference/sdk": "sdk/index",
    "api-reference/index": "sdk/index",
}
